### ISSUE TITLE
Display Disaster Photo on Tease

### ISSUE THREAD

**Issue by ascalamogna** [worldbank-cdrp/historic-risk-explorer#18]
@maxgrossman I'll add a photo for each disaster in the assets folder. Let me know if there's any specific naming convention you'd prefer to use. We can do this as an inline-style for background images.

**Comment by maxgrossman** [comment]
this exists in [feature/disaster-header-photo](https://github.com/worldbank-cdrp/historic-risk-explorer/tree/feature/disaster-header-photo) and is awaiting review in #43
