### ISSUE TITLE
Identify satellite imagery for the disasters

### ISSUE THREAD

**Issue by mileswwatkins** [worldbank-cdrp/historic-risk-explorer#2]
We'll need pre- and post-disaster imagery for the disasters.

Here's the list:

<img width="239" alt="screen shot 2017-06-02 at 10 37 00" src="https://cloud.githubusercontent.com/assets/4959135/26745556/10927de6-47b9-11e7-9774-46030441629f.png">

- [ ] Pakistan 2005 earthquake
- [x] Pakistan 2010 flood
- [x] Haiti 2010 earthquake
- [x] Fiji 2016 hurricane
- [ ] Armenia 1988 earthquake
- [ ] El Salvador 2001 earthquake
- [x] Mozambique 2015 flood
- [ ] ~~Dominican Republic 1930 hurricane~~
- [ ] ~~Tambora 1815 volcano~~
- [ ] Chile 2010 earthquake

For now, let's focus on the modern-era ones ;)

**Comment by mileswwatkins** [comment]
cc @maxgrossman @drewbo

**Comment by drewbo** [comment]
To confirm the intent here, images will be used for context in either sidebars or as an overlay but aren't required for any detailed analysis. cc: @mileswwatkins 

Did quick voice with @maxgrossman on this: use Digital Globe (~30cm) where made freely available, the Fiji Hurricane will have Landsat-8 (15/30m) and Sentinel-2 (10/20m), anything prior to that the best bet is either Landsat-5 (30m) or MODIS (250m). Also worth searching https://earthexplorer.usgs.gov/ for some of the more esoteric satellites and other providers for free imagery (Planet, old Terra Bella) if you don't get hits from other options.

**Comment by maxgrossman** [comment]
# Found sources

## Pakistan
- 2010 flood
  - Landsat scenes to use.
- pre: 

LT05_L1TP_151036_20100524_20161015_01_T1
           LT05_L1TP_151037_20100524_20161016_01_T1
           LT05_L1TP_151038_20100524_20161016_01_T1

- post:

 LT05_L1TP_151036_20100812_20161014_01_T1
            LT05_L1TP_151037_20100812_20161014_01_T1
            LT05_L1TP_151038_20100812_20161014_01_T1
  - why?
    - The area shown in these scenes is pretty urbanized, see the pdf below for proof. It is also an area where cities along the indus and other rivers were pretty universally flooded.
    http://reliefweb.int/sites/reliefweb.int/files/resources/4A1E711F9BE79819852577890071CD67-map.pdf

## Haiti
  - January 12th 2010 earthquake
    - [Imagery, Thanks to DG](https://www.digitalglobe.com/opendata/haiti/pre-event)
    - why use it?
      - We can get images of pre/post imgs port-au-prince

## Chile
  - 2010 Eq
    - many sources found [here](http://wiki.openstreetmap.org/wiki/2010_Chile_earthquake/Imagery_and_data_sources) at this link, but the two WMS I found might be best. Note, being that they're WMS
    - why?
      - there was a reported chemical fire. The post (or day of) imagery (I am pretty certain) shows it.
        - See section 'Damages and Casualties' in [proof of fire a](https://en.wikipedia.org/wiki/2010_Chile_earthquake)
        - See section 'Aftershocks' in [proof of fire b](http://news.bbc.co.uk/2/hi/8540289.stm)
      - [pre santiago](http://hazardmap.service-section.com/cgi-bin/mapserv?map=/map/UserRaster/alos_avnir2_chile_santiago_north_20090224.map&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=alos_avnir2_chile_santiago_north_20090224&STYLES=&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image/png&SRS=EPSG:4326&)

      - [post-santiago](http://hazardmap.service-section.com/cgi-bin/mapserv?map=/map/UserRaster/alos_avnir2_chile_santiago_north_20100227.map&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=alos_avnir2_chile_santiago_north_20100227&STYLES=&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image/png&SRS=EPSG:4326&)

# Pakistan Images 

<img width="502" alt="pakistan-post" src="https://user-images.githubusercontent.com/15100429/26891224-3c87c880-4b82-11e7-911d-fc0e93dbb574.png">
<img width="513" alt="pakistan-pre" src="https://user-images.githubusercontent.com/15100429/26891223-3c82bf02-4b82-11e7-84ad-50ed1679b213.png">

# Santiago Images
<img width="533" alt="santiago-post" src="https://user-images.githubusercontent.com/15100429/26891233-478da7f4-4b82-11e7-988e-1e3159e5fb34.png">
<img width="610" alt="santiago-pre" src="https://user-images.githubusercontent.com/15100429/26891234-47907f6a-4b82-11e7-9668-db42244b1ae8.png">

@mileswwatkins @drewbo 

I'm going to give missing maps some time until @drewbo and i chat later on.

**Comment by maxgrossman** [comment]
@mileswwatkins 
@drewbo 

Regarding freeness of imagery & terms of use

- [Haiti](https://www.digitalglobe.com/opendata/haiti/license)
- [Pakistan](http://glcf.umd.edu/data/landsat/)

Regarding the firey Santiago image.

Since a fire doesn't evoke questions of infrastructure strenght the way building destruction does, we are going to nix the idea. There's a nice [illustration](http://reliefweb.int/sites/reliefweb.int/files/resources/30D44BE092DFA594852576E0007DE309-map.pdf) of inundation in a coastal city, Contitución, but it looks like the damage is tsunami based (not from the earthquake) and the imagery comes from rapidEye which is 1) proprietary and may be only available for the disaster and 2) comes form wms's that are so awesomely unavailable right now.

With that said I'll take time tomorrow to look for sentinal-2, landsat 8 stuff for Mozambique and Fiji, highlight where in the Haiti image there is noticable innundation, and come back to Chile to see if there's imagery I'm being a bum at not seeing/noticing. 

Thanks for the include on the project.

**Comment by maxgrossman** [comment]
### Mozambique/Malawi 2015 Floods

- Note. Phalombe is in Southeastern Malawi on border with Mozambique.

- Clear flooding around Nsanje, town at border of Malawi and Mozambique

    - post :  [2-15-2015](http://landsat-pds.s3.amazonaws.com/L8/167/072/LC81670722015046LGN00/index.html)
    - pre : [12-13-2014](http://landsat-pds.s3.amazonaws.com/L8/167/072/LC81670722014347LGN00/index.html)

  - Clear floods in Phalombe, Malawi

    - post : [2-15-2015](http://landsat-pds.s3.amazonaws.com/L8/167/071/LC81670712015046LGN00/index.html)
    - pre : [12-13-2015](http://landsat-pds.s3.amazonaws.com/L8/167/071/LC81670712014347LGN00/index.html)

  - clear flooding in Quelimane, though clouds are very present

    - post : [02-08-2015](http://landsat-pds.s3.amazonaws.com/L8/166/072/LC81660722015039LGN00/index.html)
    - pre : [12-22-2014](http://landsat-pds.s3.amazonaws.com/L8/166/072/LC81660722014356LGN00/index.html)

### Nsanje 

![nsanje-post](https://user-images.githubusercontent.com/15100429/26930359-2a2748ec-4c2b-11e7-95c4-efbeea54c043.png)
![nsanje-pre](https://user-images.githubusercontent.com/15100429/26930315-ff99f73c-4c2a-11e7-9fdc-46a6485cc67e.png)

### Quelimane

![quelimane-post](https://user-images.githubusercontent.com/15100429/26930336-100ec020-4c2b-11e7-96dc-78c4b564d8b0.png)
![quelimane-pre](https://user-images.githubusercontent.com/15100429/26930335-100b0782-4c2b-11e7-8716-bce43389a8c6.png)

### Phalombe
![phalombe-post](https://user-images.githubusercontent.com/15100429/26930343-17250d74-4c2b-11e7-8d65-5baea6566044.png)
![phalombe-pre](https://user-images.githubusercontent.com/15100429/26930344-172c40f8-4c2b-11e7-9861-822e4b37bc08.png)

@mileswwatkins, @drewbo

**Comment by maxgrossman** [comment]
# Fiji Hurricane 

- building destruction is 'hardish' to pull out, so one route we can take is crop destruction. Its very visible and pervasive in Tavua, the hardest hit part of Fiji during Winston. Those brown splotches are destroyed crops. There might be some band combinations that make this more visible than it is in False Color IR. Matt Gibb from AmCross did this after Hurricane Matthew [here](https://twitter.com/search?l=&q=from%3Agiblet22%20since%3A2016-09-01%20until%3A2016-11-30&src=typd&lang=en)

- Note. I didn't do it with Malawi, Mozambique imagery, but the links below let you pan around in a web map! Thanks sentinal at aws @drewbo for stearing me to the tool.

- post : [03-03-2016](http://apps.sentinel-hub.com/eo-browser/#lat=-17.55014009300486&lng=177.6696538925171&zoom=14&datasource=Sentinel-2%20L1C&time=2016-03-03&preset=1_TRUE_COLOR)

- pre : [01-23-2016](http://apps.sentinel-hub.com/eo-browser/#lat=-17.55014009300486&lng=177.6696538925171&zoom=14&datasource=Sentinel-2%20L1C&time=2016-01-23&preset=2_FALSE_COLOR)



![tavua-pre](https://user-images.githubusercontent.com/15100429/26932053-649a2936-4c30-11e7-91c4-a471a87a3950.png)
![tavua-post](https://user-images.githubusercontent.com/15100429/26932054-649d8bbc-4c30-11e7-8921-6c60324f0ba1.png)

@mileswwatkins

**Comment by maxgrossman** [comment]
^ band combo 751 seems to work nicely. Still makes vegetation red, which people sometimes find hard to interpret.

@mileswwatkins @drewbo

**Comment by maxgrossman** [comment]
### Post Haiti Images

I'm downing the pre-images right now, but thought I'd share some clear building destruction. 
I'm making a geojson w/points of these destroyed buildings. Once the pre-images are downloaded will share pre-image screen shots. 

![pre-haiti-1](https://user-images.githubusercontent.com/15100429/26976493-fbbe4ec0-4cf1-11e7-83a4-b92e7f528808.png)
![post-haiti-1](https://user-images.githubusercontent.com/15100429/26976491-fbb93f70-4cf1-11e7-88dc-ad9bffe63fa9.png)
![post-haiti-2](https://user-images.githubusercontent.com/15100429/26976492-fbb9aea6-4cf1-11e7-917d-77b3b9f46868.png)
![pre-haiti-2](https://user-images.githubusercontent.com/15100429/26976494-fbbf2d90-4cf1-11e7-8a2b-46ff587c0313.png)



@mileswwatkins @drewbo

**Comment by maxgrossman** [comment]
I sent a preview of this to miles last night, but here's a updated/with-links draft.
---
Dear Xijie,

I hope you are well. We've identified 'pre' and 'post' disaster imagery for the disasters you listed.
Can you give the imagery a look to see if it illustrates what you had in mind?

- 2010 Pakistan Floods

  - These Landsat images illustrate flooding in urban areas within the Indus river basin.

     - [Pre-disaster](https://user-images.githubusercontent.com/15100429/26891223-3c82bf02-4b82-11e7-84ad-50ed1679b213.png)
     - [Post-disaster](https://user-images.githubusercontent.com/15100429/26891224-3c87c880-4b82-11e7-911d-fc0e93dbb574.png)

Note that the following images use a method of visualizing satellite imagery called 'false color IR'. This method makes vegetated areas pronounced, red, and distinct from water bodies & rivers, and soil. For showing flooding and vegetation loss, it is quite helpful.

- 2015 Mozambique/Malawi Floods

  - Similar to the Pakistan scenes, these images show serious flooding in populated areas.

    - [Njsanje, Pre-disaster](http://apps.sentinel-hub.com/eo-browser/#lat=-16.822287977821773&lng=35.09925842285156&zoom=10&datasource=Landsat%208%20USGS&time=2014-12-13&preset=2_FALSE_COLOR)
    - [Njsanje, Post-disaster](http://apps.sentinel-hub.com/eo-browser/#lat=-16.822287977821773&lng=35.09925842285156&zoom=10&datasource=Landsat%208%20USGS&time=2015-02-15&preset=2_FALSE_COLOR)

    - [Phalombe, Pre-disaster](http://apps.sentinel-hub.com/eo-browser/#lat=-15.804476668284687&lng=35.55072784423828&zoom=11&datasource=Landsat%208%20USGS&time=2014-12-13&preset=2_FALSE_COLOR)
    - [Phalombe, Post-disaster](http://apps.sentinel-hub.com/eo-browser/#lat=-15.804476668284687&lng=35.55072784423828&zoom=11&datasource=Landsat%208%20USGS&time=2015-02-15&preset=2_FALSE_COLOR)

    - [Quelimane, Pre-disaster](http://apps.sentinel-hub.com/eo-browser/#lat=-17.835642582889573&lng=36.82960510253906&zoom=10&datasource=Landsat%208%20USGS&time=2014-12-22&preset=2_FALSE_COLOR)
    - [Quelimane, Post-disaster](http://apps.sentinel-hub.com/eo-browser/#lat=-17.835642582889573&lng=36.82960510253906&zoom=10&datasource=Landsat%208%20USGS&time=2015-02-08&preset=2_FALSE_COLOR)

- 2016 Fiji Cyclone

  - Here, crop destruction is most noticeable. The brown splotches in the post-disaster images are destroyed crops.

    - [Tavua, Pre-disaster](http://apps.sentinel-hub.com/eo-browser/#lat=-17.545679999829797&lng=177.66051292419434&zoom=13&datasource=Sentinel-2%20L1C&time=2016-01-23&preset=2_FALSE_COLOR)
    - [Tavua, Post-disaster](http://apps.sentinel-hub.com/eo-browser/#lat=-17.545598162232118&lng=177.6605987548828&zoom=13&datasource=Sentinel-2%20L1C&time=2016-03-03&preset=2_FALSE_COLOR)

- 2010 Haiti Earthquake

  - High resolution imagery makes building destruction visible in these images.

    - [Port-au-Prince 1, Pre-disaster](https://user-images.githubusercontent.com/15100429/26976494-fbbf2d90-4cf1-11e7-8a2b-46ff587c0313.png)
    - [Port-au-Prince 1, Post-disaster](https://user-images.githubusercontent.com/15100429/26976492-fbb9aea6-4cf1-11e7-917d-77b3b9f46868.png)

    - [Port-au-Prince 2, Pre-disaster](https://user-images.githubusercontent.com/15100429/26976493-fbbe4ec0-4cf1-11e7-83a4-b92e7f528808.png)
    - [Port-au-Prince 2, Pre-disaster](https://user-images.githubusercontent.com/15100429/26976491-fbb93f70-4cf1-11e7-88dc-ad9bffe63fa9.png)

Regarding the the disasters you provided that we did not include imagery for.

As earthquakes, these disasters really need high-resolution imagery to show pronounced disaster effects (building/road destruction, coastal uplift). Public domain imagery does not exist for these cases. Some of the coarser resolution imagery is able to show immediate effects of earthquakes - particularly a chemical fire after the 2010 Chile earthquake. However, we decided that fires are situational disaster effect, not speaking to the greater question of 'disaster-risk'. So, we decided to omit it.

We look forward to your thoughts.

Best,

Miles

---
@mileswwatkins @drewbo

**Comment by maxgrossman** [comment]
@mileswwatkins  -- some better examples of prepost fiji imagery

pre
![pre-cyclone](https://user-images.githubusercontent.com/15100429/27484156-32ca7c90-57f6-11e7-9c50-87d88c7e9e7b.png)
post
![post-cyclone](https://user-images.githubusercontent.com/15100429/27484158-32cda3c0-57f6-11e7-8ee5-660a8ab5cc32.png)
pre
![post-cyclone1](https://user-images.githubusercontent.com/15100429/27484166-348dcd0c-57f6-11e7-9bdb-32b1230681d5.png)
post
![pre-cyclone1](https://user-images.githubusercontent.com/15100429/27484165-348c7b50-57f6-11e7-9d0c-dc929bd2ecc4.png)
pre
![pre-cyclone2](https://user-images.githubusercontent.com/15100429/27484170-37e7d394-57f6-11e7-8e8b-e51923bc0539.png)
post
![post-cyclone2](https://user-images.githubusercontent.com/15100429/27484169-37e73ac4-57f6-11e7-84d6-0f7a95981ee9.png)
pre
![post-cyclone3](https://user-images.githubusercontent.com/15100429/27484172-37eb6874-57f6-11e7-9d2b-dd817b14350e.png)
post
![pre-cyclone3](https://user-images.githubusercontent.com/15100429/27484171-37e89e5a-57f6-11e7-8b0a-d833b717d346.png)

**Comment by mileswwatkins** [comment]
Generally completed. Nice job @maxgrossman!
