### ISSUE TITLE
Populate Profile Page with Correct Data

### ISSUE THREAD

**Issue by ascalamogna** [worldbank-cdrp/historic-risk-explorer#22]

**Comment by maxgrossman** [comment]
the [`feature/hookup-data`](https://github.com/worldbank-cdrp/historic-risk-explorer/tree/feature/hook-up-data) includes disaster specific data for all metrics except annualized loss and exposure. So too does the map on this branch show the map layers' exposure, annualized loss, and loss ratio values 'on hover'.

What is left for this branch is figuring out how to generate values for historic and modeled annualized loss and exposure so they can be added to the [constants.js](https://github.com/worldbank-cdrp/historic-risk-explorer/blob/feature/hook-up-data/app/assets/scripts/constants.js#L43) file that powers each disaster profile. These values are not apparently available in the risk profiles.
