### ISSUE TITLE
Hookup Download Profile Button

### ISSUE THREAD

**Issue by ascalamogna** [worldbank-cdrp/historic-risk-explorer#24]
Add ability for users to download profile pdfs. @mileswwatkins do we have all of these?

**Comment by mileswwatkins** [comment]
Last time I looked, we have "alpha" versions of all of them.

**Comment by maxgrossman** [comment]
download links exist in  the [`feature/download-links`](https://github.com/worldbank-cdrp/historic-risk-explorer/tree/feature/download-links) branch.

The Pakistan 2010 floods profile seems to be corrupted, however. a correct file here plus merging the branch will close this
