### ISSUE TITLE
Add Before and After Slider

### ISSUE THREAD

**Issue by ascalamogna** [worldbank-cdrp/historic-risk-explorer#29]
@maxgrossman let's work together on this. If you can create this very roughly I can help with styling.

**Comment by maxgrossman** [comment]
for our notes - map added, styled, and merged with #33 ; next step is to handle satellite imagery processing, uploading it to mapbox, then including it in the site's config accordingly.

**Comment by maxgrossman** [comment]
update - the [`feature/pre-post-imagery`](https://github.com/worldbank-cdrp/historic-risk-explorer/tree/feature/pre-post-imagery) branch implements imagery in the slider. what is left is to process and add to mapbox imagery all disasters and do any additional styling, ui changes necessary
