### ISSUE TITLE
Remaining Imagery Pipe work

### ISSUE THREAD

**Issue by maxgrossman** [worldbank-cdrp/historic-risk-explorer#48]
Remaining imagery work is ticketed out in #49, #50, #51 this ticket includes some info to be cognizant of when working on them

##### contrast enhancement

- to fiddle with the contrast enhancement settings for a single image, change the [percent](https://github.com/worldbank-cdrp/historic-risk-explorer/blob/enhancement/dockerize/lib/sat-processing/dip.py#L30) used to set the standard deviation stretch on bands
- histogram match before and after images
  - I did not find it useful for the landsat5 scenes processed, but it might be worth histogram matching the pre-post images of other disasters' scenes. The function to do so is [here](https://github.com/worldbank-cdrp/historic-risk-explorer/blob/enhancement/dockerize/lib/sat-processing/dip.py#L40). Info about the package used is [here](https://github.com/mapbox/rio-hist)
  - BIG NOTE - rio-hist outputs a geotiff with a 4th alpha band which can't be mosaiced with a 3-band stacked image. This should not matter for simple histogram matching, but if mosaicing is needed down the line, the alpha will need to be removed with the [remove_alpha function](https://github.com/worldbank-cdrp/historic-risk-explorer/blob/enhancement/dockerize/lib/sat-processing/dip.py#L126)

 ##### scene ids

- if new sentinal scenes are added to the config, the id needed is outputted when a sat-search command is appended with —printmd for example
  - `sat-search --date 2016-01-23 --satellite_name sentinel --printmd`

##### mosaicing

- mosaicing for non-dg images only supports 2 images, though this is an easy [refactor](https://github.com/worldbank-cdrp/historic-risk-explorer/blob/enhancement/dockerize/lib/sat-processing/dip.py#L54) as the gdalwarp, the command used for mosaicing, can be given multiple >2 args.

**Comment by mileswwatkins** [comment]
Split into its constituent issues.
