### ISSUE TITLE
Generate sentinel 2 images. 

### ISSUE THREAD

**Issue by maxgrossman** [worldbank-cdrp/historic-risk-explorer#50]
- todos: add an additional step before contrast enhancement to convert jp2s to GeoTIFF and add mosaic to the config for the sentinel2 images
  - the conversion is probably as simple as `gdal_translate -of GTiff input.jp2 output.tif `
  - only the post imagery needs to be mosaiced
  - potential gotchas: 
     - like dg, these images are kinda large.
     - the pre and post footprints are probably different so one might need be clipped to the extent of the other

**Comment by mileswwatkins** [comment]
Copying from https://github.com/worldbank-cdrp/historic-risk-explorer/issues/48:

> if new sentinal scenes are added to the config, the id needed is outputted when a sat-search command is appended with —printmd for example `sat-search --date 2016-01-23 --satellite_name sentinel --printmd`
