### ISSUE TITLE
Fix webpage name

### ISSUE THREAD

**Issue by mileswwatkins** [worldbank-cdrp/historic-risk-explorer#66]
Right now it just displays the path, instead of a clean webpage name, eg:

<img width="270" alt="screen shot 2017-11-15 at 17 47 11" src="https://user-images.githubusercontent.com/4959135/32864413-0db6ff4c-ca2d-11e7-8592-66346c99404c.png">
<img width="347" alt="screen shot 2017-11-15 at 17 47 20" src="https://user-images.githubusercontent.com/4959135/32864414-0dc4a822-ca2d-11e7-8f55-f41a409070ad.png">

**Comment by ridixcr** [comment]
My Changes
![](https://user-images.githubusercontent.com/1646072/36047522-6139415a-0daa-11e8-8700-a0214e119670.png)

suggestions :bowing_man:
