### ISSUE TITLE
Fix path for footprint images

### ISSUE THREAD

**Issue by ascalamogna** [worldbank-cdrp/historic-risk-explorer#85]
The paths for footprint images aren't being correctly generated in the staging site.

**Comment by olafveerman** [comment]
The way we are loading the assets, doesn't allow for the site url to have a subpath 
https://github.com/worldbank-cdrp/historic-risk-explorer/blob/c6361c2170a43a15fea9d52de957c0a47be0b4bb/app/assets/scripts/utils/map.js#L102

The staging site is hosted on Github Pages on: `https://worldbank-cdrp.github.io/historic-risk-explorer`
The app tries to load the assets from `https://worldbank-cdrp.github.io/assets`

We should add the base-url to the config, much like we're doing here:

**Comment by ridixcr** [comment]
They could update staging site, I explicitly assign the URL of the Footprints before rendering them on the map.
![](https://user-images.githubusercontent.com/1646072/36048333-deee0a3e-0dac-11e8-933b-fa414664a494.png)

cc. @danielfdsilva @olafveerman @ascalamogna
