### ISSUE TITLE
Move tooltip value from key to map 

### ISSUE THREAD

**Issue by ascalamogna** [worldbank-cdrp/historic-risk-explorer#88]
The value should appear in a tooltip next to a place on the map rather than in the key.

**Comment by ascalamogna** [comment]
This is in progress by @Rub21

**Comment by Rub21** [comment]
@ascalamogna I've made this 👇 , I am having problems calling the numbers as in the legend, could you help me with that? 

![ff3](https://user-images.githubusercontent.com/1152236/36875759-628434c2-1d7f-11e8-9afe-fa14adba776c.gif)

https://github.com/worldbank-cdrp/historic-risk-explorer/tree/popup
