### ISSUE TITLE
Style compare map

### ISSUE THREAD

**Issue by olafveerman** [worldbank-cdrp/historic-risk-explorer#92]
There are some default Mapbox styles that mess up the compare map on the bottom of a disaster page:

![image](https://user-images.githubusercontent.com/751330/36503931-d8a04e48-171c-11e8-9f22-887cfc9150fc.png)

Removing `overflow: hidden;` from `.mapboxgl-map` results in this:

![image](https://user-images.githubusercontent.com/751330/36503879-a88743ce-171c-11e8-85d2-af2eebd72bb2.png)

**Comment by ascalamogna** [comment]
@olafveerman I think there's something wrong with the slider, when I try to remove the `overflow: hidden` on all elements I get this. I'm not sure it's a styling issue. Can we get a dev to look at this?

![screen shot 2018-03-01 at 4 26 57 pm](https://user-images.githubusercontent.com/6752098/36870548-78e045f6-1d6d-11e8-9c31-187cab31718b.png)
